nodeLinker: pnp

packageExtensions:
  "@hookform/resolvers@*":
    dependencies:
      yup: "*"
  html-webpack-plugin@*:
    dependencies:
      loader-utils: "*"
  ilp-packet@*:
    dependencies:
      long: "*"
  ilp-protocol-stream@*:
    dependencies:
      "@types/long": "*"
  inversify-express-utils@*:
    dependencies:
      "@types/express": "*"
      inversify: "*"
  inversify-logger-middleware@*:
    dependencies:
      inversify: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

plugins:
  - ./commands/yarn/tsconfig-paths-plugin.js
  - ./commands/yarn/check-node-version.js

yarnPath: .yarn/releases/yarn-sources.cjs
