name: Archive Extension Build And Source Code

on:
  push:
    tags:
      - coil-extension@*

jobs:
  save-monorepo-source-code:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Step 1 - Use the Upload Artifact GitHub Action to upload the monorepo
        uses: actions/upload-artifact@v2
        with: 
          name: source-${{env.RELEASE_VERSION}}
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/*.gitignore

  save-chrome-build:
    runs-on: ubuntu-latest
    needs: [ save-monorepo-source-code ]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        with:
          name: source-${{env.RELEASE_VERSION}}

      - name: Step 1 - Package the extension for chrome
        run: sh package.sh chrome
        working-directory: ${{ github.workspace }}/packages/coil-extension
    
      - name: Step 2 - Use the Upload Artifact GitHub Action to upload the extension build
        uses: actions/upload-artifact@v2
        with: 
          name: chrome-${{env.RELEASE_VERSION}}
          path: ${{ github.workspace }}/packages/coil-extension/dist
          
  save-firefox-build:
    runs-on: ubuntu-latest
    needs: [ save-monorepo-source-code ]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        with:
          name: source-${{env.RELEASE_VERSION}}

      - name: Step 1 - Package the extension for firefox
        run: sh package.sh firefox
        working-directory: ${{ github.workspace }}/packages/coil-extension
    
      - name: Step 2 - Use the Upload Artifact GitHub Action to upload the extension build
        uses: actions/upload-artifact@v2
        with: 
          name: firefox-${{env.RELEASE_VERSION}}
          path: ${{ github.workspace }}/packages/coil-extension/dist

